// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyzqidweppyvjwnmmoox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5enFpZHdlcHB5dmp3bm1tb294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjU0NDUsImV4cCI6MjA2MzgwMTQ0NX0.Dx1LZNZBPpoKtizSVobLGhAzkGI42C4KCTVoU1uMxKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);